"3.1":
  varnames:
    input: []
    output:
      - bttf
      - song
      - make_war
      - result
      - result2
      - quotient
      - quotient2
  cases:
    - input: []
      output:
        - 1985
        - Castle on the hill
        - False
        - 7
        - 10.0
        - 1.75
        - 1

"3.2":
  varnames:
    input:
      - a
      - b
      - c
    output:
      - x1
      - x2
  cases:
    - input: [2, -7, 3]
      output: [3.0, 0.5]
    - input: [-1, 7, 10]
      output: [2.0, 5.0]
    - input: [-1, -4, 4]
      output: [2.0, 2.0]
    - input: [7, 21, -28]
      output: [1.0, -4.0]

"3.3":
  varnames:
    input:
      - text
    output:
      - result
  cases:
    - input:
        - 1hello-bye2
      output:
        - HELLO|ByeBye
    - input:
        - 3go-Forest1
      output:
        - GOGOGO|Forest
